### ISSUE TITLE
Is there only the automatic mode code?

### ISSUE THREAD

**Issue by fanq15** [fidler-lab/curve-gcn#1]
It seems there is no interactive mode code.

**Comment by arieling** [comment]
Yes. Interactive mode code will be released all together with our tool platform. Stay tuned!

**Comment by fanq15** [comment]
Thanks!

**Comment by SpinachR** [comment]
> Thanks!

Hi, @fanq15 , I notice that the Curve-GCN code is not shared by the website currently. If convenient, can you send me a copy of this code through my email (ruili52-c@my.cityu.edu.hk). I am interested in this idea.

Thanks in advance.

**Comment by amlankar** [comment]
Hi @SpinachR, sharing code through e-mail is a strict violation of the license agreement. Please refrain from this, thank you

**Comment by SpinachR** [comment]
> Hi @SpinachR, sharing code through e-mail is a strict violation of the license agreement. Please refrain from this, thank you

Hi, @amlankar, I have deleted my previous message and apology for any inconvenience. However, I am very interested in this gcn-based method. Is there any method to access this code. I have already registered in your website.

**Comment by SpinachR** [comment]
> Hi @SpinachR, sharing code through e-mail is a strict violation of the license agreement. Please refrain from this, thank you

Hi, @amlankar, I have deleted my previous message and apology for any inconvenience. However, I am very interested in this gcn-based method. Is there any method to access this code. I have already registered in your website.
