### ISSUE TITLE
Some questions about Interactive mode curve.

### ISSUE THREAD

**Issue by LetsGoFir** [fidler-lab/curve-gcn#18]
![image](https://user-images.githubusercontent.com/59643844/84336067-0f330700-abc9-11ea-9dd2-2fb933509fd8.png)
They are all with CityScapes.
1. Like this figure, let's see the light blue curve named 'Our T=1'. In my opinion, you will correct all the objects until they are all with IoU 100, then why the AVG IoU is just below 90 (it should be 100)?

2. Another question, why the start IoU is about 77? In the table 1 you have IoU 73+ w/o correction.
![image](https://user-images.githubusercontent.com/59643844/84336901-e57adf80-abca-11ea-9262-69eb5cb5b44f.png)

3. When you calculate the AVG correction, do you calculate it in the way in PolygonRNN? It calculate every category's mean correction number(total_category_correction/total_category_instance_num, no matter the instance is corrected or not), and sum them then divide by 8 (8 category). Is my understanding correct？

**Comment by amlankar** [comment]
Hi, thanks for your interest in our work!

1. You are right, you can see that the graph tries to show IoU @ number of clicks by the user. Asymptotically with the number of clicks = average polygon length in the dataset (averaged per category divided by 8 as you mention in Q3), we would achieve 100 IoU. This average polygon length is beyond the x-axis limit of 16 in this graph.

2. You can see that the starting number is around 77 with non-zero number of clicks as well, the same curve at num_clicks = 0 would be at IoU around 73

3. I believe your understanding is right, but I will ask @SteveJunGao or @arieling  to confirm :)

**Comment by LetsGoFir** [comment]
> Hi, thanks for your interest in our work!
> 
> 1. You are right, you can see that the graph tries to show IoU @ number of clicks by the user. Asymptotically with the number of clicks = average polygon length in the dataset (averaged per category divided by 8 as you mention in Q3), we would achieve 100 IoU. This average polygon length is beyond the x-axis limit of 16 in this graph.
> 2. You can see that the starting number is around 77 with non-zero number of clicks as well, the same curve at num_clicks = 0 would be at IoU around 73
> 3. I believe your understanding is right, but I will ask @SteveJunGao or @arieling  to confirm :)

Thanks for your prompt reply and great work!  It seems like the correction contribute to the IoU very well, since 73 -> 77 takes a little corrections.
By the way, is there any scripts to plot the curve in PolygonRNN code? Or could you tell my how to calculate them? I think I can do it by correct the polygons  inferred on validation over and over ( for each iteration, I will correct one of the points of each polygon under T).
