### ISSUE TITLE
High precison masks

### ISSUE THREAD

**Issue by bhack** [fidler-lab/curve-gcn#2]
Have you evaluated the performance on high quality masks like Davis?

https://davischallenge.org/challenge2019/index.html

**Comment by arieling** [comment]
No. Davis doesn't have polygon data so we can't train curve-gcn on it.

We have another paper on CVPR this year beats STOA of Davis. Stay tuned!

**Comment by bhack** [comment]
I suppose that Davis binary masks could be quite easy traced in polygon/splines. What was the problem?

**Comment by arieling** [comment]
Curve-gcn / polyrnn take sparse polygon data rather than binary mask data as input. Davis is annotated by pixel-wise so it doesn't have sparse polygon data. We can use CV2 to estimate a dense polygon by binary mask however it's not the purpose of polyrnn/curve-gcn.

**Comment by bhack** [comment]
I know. I meant you can use some simple tool/algo like the [Potrace](http://potrace.sourceforge.net/) to just to emit splines over the binary mask. 
But was just to check the metrics on very high quality annotation.
