### ISSUE TITLE
Incorrect prediction scipt

### ISSUE THREAD

**Issue by YanShuo1992** [fidler-lab/curve-gcn#4]
It seems like the prediction scipt is incorrect.  
Moreover, could you please tell me more details on how to use manual mode?  I modify the gnn-active-spline-diff-render.json and only get some png result.

I aslo get some warrning:

/home/yan/workspace/curve_gcn_release/code/active_spline/ActiveSplineDiffIOU.py:5: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

**Comment by SteveJunGao** [comment]
The prediction script is used to generate predictions (the png results you see), you need to run ``Scripts/get_scores.py`` and ``Scripts/get_score_boundary_F.py`` to get the IOU and F-score in our paper. 

For the warnings, just ignore it, it doesn't influence the results.

**Comment by YanShuo1992** [comment]
@SteveJunGao Sorry, I didn't make it clear.  The prediction script in the README is:
python Scripts/train/train_gnn_active_spline_diffrender.py --exp <path to exp file> --output_dir <path to output dir> --reload <path to checkpoint> 

However, I am more interested in the interactive mode.  Is there script for it?  Could you give me more details?

Cheers

**Comment by amckay1** [comment]
I too am unsure how the interactive mode was supposed to be accessed. Thank you for your help!

**Comment by arieling** [comment]
Sorry interactive mode is not available at this moment. Online Demo will be available soon.

**Comment by Jacoobr** [comment]
Hi, @arieling . Would you mind to tell me when the 'online interactive tools' code will be publised? Because i want your great tools to get annotation scripts of prosate of my research and the annotation by human in the loop is so time consuming. Appreciative for your reply.

**Comment by wenmengliu** [comment]
Hi, @SteveJunGao  I noticed that there is a minor error in the 'Readme' for generating prediction masks. The path should be `` python Scripts/prediction/generate_annotation_from_active_spline.py --exp <path to exp file> --output_dir <path to output dir> --reload <path to checkpoint> `` I feel very interested in your work. Thanks for sharing :)-

**Comment by SteveJunGao** [comment]
Hi @wenmengliu, thank you for pointing this out. You're right, the path is wrong and we have updated the README, thanks.
