### ISSUE TITLE
Cannot access to download page

### ISSUE THREAD

**Issue by sdxass** [fidler-lab/curve-gcn#9]
Hi,

First of all, thanks for open sourcing such a great piece of work. Currently, I cannot access to the "signup" page to download the code. Could you please check this issue?

Any response will be helpful. Thank you again for your wonderful work.

**Comment by zhangxiaoya** [comment]
I can access signup page, but got an error after submit.

> SQL Connection failed: Connection refused
Please contact curvegcn@cs.toronto.edu

**Comment by insikk** [comment]
@zhangxiaoya same here. Any update?

**Comment by phongnhhn92** [comment]
I am having the same issue here.

**Comment by weisq2691** [comment]
Keep waiting for a response…

**Comment by Alex6D** [comment]
Excellent Work, waiting for the response.

**Comment by arieling** [comment]
We are currently refactoring the code and not sharing. Please check back at another
time. 
In the meantime, polygon-rnn code can be downloaded.
Thank you for your patience.
